name: Tests
env:
  RAILS_ENV: test

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-pr-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-pr-
      - name: Setup
        run: |
          bundle install
          bundle exec rake --trace db:create db:schema:load db:seed
      - name: Test
        run: |
          bundle exec rake spec
