name: Tests
env:
  OX_AR_DB_USER: postgres
  OX_AR_TEST_DB: ci_test
  OX_AR_DB_PASS: postgres
  RAILS_ENV: test

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:11
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USER: ${{ env.OX_AR_DB_USER }}
          POSTGRES_DB: ${{ env.OX_AR_TEST_DB }}
          POSTGRES_PASSWORD: ${{ env.OX_AR_DB_PASS }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-pr-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-pr-
      - name: Setup
        run: |
          bundle install
          bundle exec rake --trace db:create db:schema:load db:seed
      - name: Test
        run: |
          bundle exec rake spec
