name: Tests
env:
  RAILS_ENV: test

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        RAILS_VERSION:
          - 6.1.1
          - 7.0.8
          - 7.1.3
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.RAILS_VERSION }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.RAILS_VERSION }}-gems-
      - name: Setup
        env:
          RAILS_VERSION: ${{ matrix.RAILS_VERSION }}
        run: |
          bundle install
          bundle exec rake --trace db:create db:schema:load db:seed
      - name: Test
        env:
          RAILS_VERSION: ${{ matrix.RAILS_VERSION }}
        run: bundle exec rake spec
